version: '3.8'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: faat
      POSTGRES_PASSWORD: faat
      POSTGRES_DB: escola
    ports:
      - "3000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python_application
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_NAME=${POSTGRES_DB:-app_database}
      - DATABASE_USER=${POSTGRES_USER:-postgres}
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: